server:
  port: 6010

mybatis:
  type-aliases-package: org.jxx.dao
  mapper-locations: classpath:table/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
spring:
  application:
    name: jxx-product-service
#DB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
#nacos
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848